CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
    post_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    post_uploader_id INTEGER NOT NULL,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    post_description VARCHAR NOT NULL,
    image_url VARCHAR,
    video_url VARCHAR
);

CREATE TABLE IF NOT EXISTS post_likes (
    post_id INTEGER NOT NULL,
    post_user_like_id INTEGER NOT NULL
);